"""
Email alert sender — renders alerts as an HTML digest and sends via SMTP SSL.

Credentials read from environment variables (set in .env file):
  SMTP_USER, SMTP_PASSWORD, SMTP_HOST, SMTP_PORT
  ALERT_EMAIL_FROM, ALERT_EMAIL_TO

Usage:
  python -m alerts.email_sender             # evaluate rules + send
  python -m alerts.email_sender --dry-run   # print HTML, do not send
"""
import argparse
import smtplib
import sys
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import List, Dict, Any

from dotenv import load_dotenv

from config.settings import (
    ALERT_EMAIL_FROM, ALERT_EMAIL_TO,
    SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD,
    DB_PATH,
)
from alerts.alert_rules import evaluate_all_rules

load_dotenv(Path(__file__).resolve().parent.parent / ".env")

_LEVEL_COLOR = {
    "CRITICAL": "#dc3545",
    "WARNING":  "#fd7e14",
    "INFO":     "#0d6efd",
}


def _build_html(alerts: List[Dict[str, Any]]) -> str:
    rows = ""
    for a in alerts:
        color = _LEVEL_COLOR.get(a["level"], "#6c757d")
        rows += f"""
        <tr>
          <td style="padding:8px;border-bottom:1px solid #dee2e6;">
            <span style="color:{color};font-weight:bold;">{a['level']}</span>
          </td>
          <td style="padding:8px;border-bottom:1px solid #dee2e6;">{a['rule']}</td>
          <td style="padding:8px;border-bottom:1px solid #dee2e6;">{a['message']}</td>
        </tr>"""

    critical_count = sum(1 for a in alerts if a["level"] == "CRITICAL")
    warning_count  = sum(1 for a in alerts if a["level"] == "WARNING")

    return f"""
    <html><body style="font-family:Arial,sans-serif;max-width:900px;margin:auto;">
      <h2 style="color:#212529;">FlowSight Alert Digest</h2>
      <p style="color:#6c757d;">
        <strong>{len(alerts)}</strong> alerts &mdash;
        <span style="color:#dc3545;">{critical_count} CRITICAL</span>,
        <span style="color:#fd7e14;">{warning_count} WARNING</span>
      </p>
      <table style="width:100%;border-collapse:collapse;font-size:14px;">
        <thead>
          <tr style="background:#f8f9fa;">
            <th style="padding:8px;text-align:left;border-bottom:2px solid #dee2e6;">Level</th>
            <th style="padding:8px;text-align:left;border-bottom:2px solid #dee2e6;">Rule</th>
            <th style="padding:8px;text-align:left;border-bottom:2px solid #dee2e6;">Detail</th>
          </tr>
        </thead>
        <tbody>{rows}</tbody>
      </table>
      <p style="color:#adb5bd;font-size:12px;margin-top:24px;">
        Generated by FlowSight &mdash; Supply Chain Intelligence Platform
      </p>
    </body></html>
    """


def send_alerts(dry_run: bool = False, db_path=DB_PATH) -> None:
    alerts = evaluate_all_rules(db_path=db_path, send_email=False)

    if not alerts:
        print("[email_sender] No alerts to send.")
        return

    html = _build_html(alerts)

    if dry_run:
        print("[email_sender] DRY RUN — HTML digest:")
        print(html)
        return

    if not SMTP_USER or not SMTP_PASSWORD:
        print("[email_sender] SMTP credentials not configured in .env — skipping send.")
        print(f"  Set SMTP_USER and SMTP_PASSWORD in .env to enable emails.")
        return

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"FlowSight: {len(alerts)} Supply Chain Alerts"
    msg["From"]    = ALERT_EMAIL_FROM
    msg["To"]      = ALERT_EMAIL_TO
    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT) as server:
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.sendmail(ALERT_EMAIL_FROM, [ALERT_EMAIL_TO], msg.as_string())
        print(f"[email_sender] Sent {len(alerts)} alerts to {ALERT_EMAIL_TO}")
    except Exception as e:
        print(f"[email_sender] Failed to send email: {e}", file=sys.stderr)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true",
                        help="Print HTML without sending email")
    args = parser.parse_args()
    send_alerts(dry_run=args.dry_run)
